FILENAME_DATE_FORMAT = "%Y%m%d"
FILENAME_DATE_COL = "filename_date"
FILENAME_DATE_FORMAT_PYSPARK = "yyyyMMdd"


IS_ENABLE_SHUFFLE_EACH_BATCH = True
IS_USE_CUDF_AT_DATALOADER = True
IS_USE_MEMORY_CACHE = True
IS_USE_GPU_BATCHDATASET = False
IS_DEBUG_PRINT_TIMEIT = True
IS_ENABLE_SHUFFLE_BASE_ON_WEEK = False
EVALUATE_FOR_INFERING_USER_ONLY = True
NUM_SAMPLE_FOR_FEATURE_IMPORTANCE = 100
MAX_FULL_TRAINED_EPOCHS = 5
FULL_TRAINED_LR = 0.01
ENABLE_LOGGING_LOSS = True