infer_date: 20230430
model_name: "dhashdlrm"
num_days_to_train: 90
data_path: "/home/giang/VNPTAI/feature_store/data/processed/preprocessed_features/features"
# using pyspark must set IS_USE_MEMORY_CACHE to False
cpu_process_lib: "pandas"
model_config_path: "model_configs/models/"
use_mlflow_tracking_server: False


#infer_date: 20250207
#model_name: "dhashdlrm"
#num_days_to_train: 90
#data_path: "/home/cuongit/BIGDATA/mytv_pipeline_data/data_product_with_processed_for_qa/processed/preprocessed_features/features_old/features"
## using pyspark must set IS_USE_MEMORY_CACHE to False
#cpu_process_lib: "pandas"
#model_config_path: "model_configs/models/"
#use_mlflow_tracking_server: False
